name: publish-to-medium
run-name: ${{ github.actor }} is publishing an article to Medium
on: public
jobs:
  publish-to-medium:
    runs-on: ubuntu-latest
    steps:
    - name: Call ZollettaReadings-publishToMedium Lambda
      id: publishToMedium
      uses: gagoar/invoke-aws-lambda@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FunctionName: ZollettaReadings-publishToMedium
        Payload: '{ "myParameter": false }'
    - name: Store response payload to file
      run: echo '${{ fromJSON(steps.publishToMedium.outputs.response).Payload }}' > publishToMedium-response.json